name: volt_age_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Pacote para gerenciar o estado da aplicação
  provider: ^6.1.5
  # Ícones padrão do iOS
  cupertino_icons: ^1.0.6
  
  # Cliente MQTT para comunicação em tempo real
  mqtt_client: ^10.0.0
  
  # Para carregar variáveis de ambiente do arquivo .env
  flutter_dotenv: ^5.1.0
  
  # Para fazer chamadas HTTP (API REST)
  http: ^1.2.1
  
  # Para exibir notificações locais no dispositivo
  flutter_local_notifications: ^17.1.2
  
  # Pacote de widgets para criar medidores (gauges) visuais
  # Adicionado para corrigir os erros e implementar o medidor de umidade
  syncfusion_flutter_gauges: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Ferramentas de análise de código para manter a qualidade
  flutter_lints: ^3.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true
  
  # Define os assets que serão incluídos no app
  assets:
    - .env